### ISSUE TITLE
Fetch copilot operation JSON schema from backend

### ISSUE THREAD

**Issue by LiamSho** [MaaAssistantArknights/maa-copilot-frontend#1]
Fetch JSON schema  from https://api.prts.plus/static/maa-copilot-schema.json

This API was introduced in [MaaCopilotServer v2.0.2](https://github.com/MaaAssistantArknights/MaaCopilotServer/releases/tag/2.0.2)

**Comment by martinwang2002** [comment]
Backend uses 
```
"$schema": "http://json-schema.org/draft-06/schema",
```

For frontend [Another JSON Schema Validator](https://ajv.js.org), it is required to use 
```
"$schema": "http://json-schema.org/draft-07/schema",
```

It is possible to do a ugly converstion.
Any other ideas?

**Comment by GalvinGao** [comment]
If backend supports `draft-07` specification then I would suggest to migrate the schema to `draft-07` instead of doing a conversion.

**Comment by LiamSho** [comment]
https://github.com/MaaAssistantArknights/MaaCopilotServer/issues/83

**Comment by LiamSho** [comment]
Fixed in backend

https://github.com/MaaAssistantArknights/MaaCopilotServer/releases/tag/2.2.4
