### ISSUE TITLE
未登陆或鉴权错误时，上传作业提示网络错误

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/maa-copilot-frontend#10]
应该提示请登陆之类的（？

![image](https://user-images.githubusercontent.com/18511905/184503137-a8a374a9-4d44-4ff5-93ab-ef70774f6a5a.png)

**Comment by MistEO** [comment]
另外作业格式错误时也是提示 “网络错误”，比如 https://github.com/MaaAssistantArknights/maa-copilot-frontend/issues/8 这种情况也是

**Comment by GalvinGao** [comment]
尬 我以为做了这个处理了.jpg

**Comment by MistEO** [comment]
要不直接显示后端返回的错误消息得了（）

**Comment by martinwang2002** [comment]
@GalvinGao Is this one already fixed?

https://github.com/MaaAssistantArknights/maa-copilot-frontend/blob/6734a46f2e396e65927f901325008e4d26f85934/src/utils/fetcher.ts

**Comment by GalvinGao** [comment]
Not yet. This is still WIP.
