### ISSUE TITLE
Copilot网站添加”找回密码“功能

### ISSUE THREAD

**Issue by HeavanDine** [MaaAssistantArknights/maa-copilot-frontend#101]
由于密码我的密码是由密码管理器自动生成；
在更换密码管理器的过程中丢失了Copilot的密码（实际上现在我已经发现了该密码），但发现没有找回密码的功能。
希望能够添加该功能。

**Comment by guansss** [comment]
用户相关的功能其实缺失了不少😥 最近会做一下
