### ISSUE TITLE
api炸了

### ISSUE THREAD

**Issue by zzz8307** [MaaAssistantArknights/maa-copilot-frontend#104]
![image](https://user-images.githubusercontent.com/25875214/208096087-40e46312-21a8-4008-a985-ca318218e5bc.png)
从今天下午开始发现炸了

**Comment by guansss** [comment]
服务器炸了是怎么会事呢？服务器炸了，其实就是服务器炸了。相信大家都很好奇，服务器为什么会炸呢？但事实就是这样，小编也感到非常惊讶……总之 @LiamSho 救救！

**Comment by MistEO** [comment]
可用性低于一个 9（

~~我们需要更多的人来发电~~

**Comment by LiamSho** [comment]
所以到底是为什么呢

这种时候我们需要进行一个艾特（

@ChingCdesu

**Comment by syorami** [comment]
是后台炸了吗，获取不到任何数据

**Comment by leonlin21** [comment]
![CleanShot-Microsoft Edge2022December18MAA CopilotexEFtRwS@2x](https://user-images.githubusercontent.com/79201728/208252736-33f22039-5d94-4438-9e13-d4e6e5e38858.png)

加载失败

**Comment by 2743d2** [comment]
```bash
curl -vv 'https://api.prts.plus/copilot/query?desc=true&limit=50&page=1&order_by=hot'
```
502 Bad Gateway

**Comment by guansss** [comment]
维护人员目前身体不适，可能需要一些时间修复，请耐心等待

**Comment by guansss** [comment]
非常抱歉，由于操作失误以及一些介质原因，服务器数据全部丢失…… 目前看来应该已无法恢复 :(

目前作业站后端正准备用 Java 重写，如果有以下经验欢迎加入我们（JDK17，Gradle，MongoDB，SpringBoot）
作业站开发群：724540644

**Comment by GalvinGao** [comment]
新版 API 已于近日上线，Closing
