### ISSUE TITLE
自动战斗/抄作业工具网站 网络连接失败

### ISSUE THREAD

**Issue by janrol** [MaaAssistantArknights/maa-copilot-frontend#106]
自动战斗/抄作业的网站在2022-12-17日发现显示加载不出来，主站副站均尝试过了是一样的。15日还是正常可以刷新并且使用的。
登陆网站则会提示网络问题，但是实际测试过其他网站都是正常的。开了VPN也是一样的，应该不是因为这个原因引起的网络异常。
截图：
![KZ@S9ON`Y6 _QALA%1D_`61](https://user-images.githubusercontent.com/59417650/208286276-e4435698-0329-4d13-b781-cf0cd434447d.png)
![O )W~COO_B$9BM$V0$(0SLO](https://user-images.githubusercontent.com/59417650/208286282-47e0db37-2be0-48ab-a406-e7d266f39362.png)

**Comment by guansss** [comment]
Duplicate of #104
