### ISSUE TITLE
模拟悖论 关卡名无法转换

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/maa-copilot-frontend#12]
[月夜魔王之剑_月见夜.zip](https://github.com/MaaAssistantArknights/maa-copilot-frontend/files/9332119/_.zip)

![image](https://user-images.githubusercontent.com/18511905/184509791-b42f2910-8a5a-4ca7-8dbb-ddafbe49ef97.png)
![image](https://user-images.githubusercontent.com/18511905/184509800-98bacdf8-9b65-44dc-b9aa-7dd8f7b3578a.png)

**Comment by MistEO** [comment]
另外还是那个问题，提示错了（

![image](https://user-images.githubusercontent.com/18511905/184509844-40dd0bff-97d6-47db-9f1b-730ac6100991.png)

link to https://github.com/MaaAssistantArknights/maa-copilot-frontend/issues/10

**Comment by MistEO** [comment]
看了下应该是 gamedata 的 stage_table.json 里没有这关，~~怎么还不如泰迪~~，可能得从别加一份 json （但没没找到模拟悖论的关卡名在哪

**Comment by MistEO** [comment]
要不改成直接从主仓库用的数据源里拿吧  https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/3rdparty/resource/Arknights-Tile-Pos/levels.json

**Comment by LiamSho** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/28832398/184512508-8ccf608a-69ca-4526-b7e0-dd5f43c6a2cf.png">

这关有啊

**Comment by martinwang2002** [comment]
The bug, `stage_name` is not changed to level id automatically for memory stages, should be fixed in #21.

However, for this json,
```
doc:
  details: "by：EadouVen"
  title: ""
```
`title` is empty string, rejected in backend.
