### ISSUE TITLE
抄作业模式，煌使用原皮，在部署干员阶段无法识别

### ISSUE THREAD

**Issue by userchild00** [MaaAssistantArknights/maa-copilot-frontend#125]
在拥有并使用音律联觉皮肤的账号上可以正常运行
没有音律联觉皮肤的账号，在干员选择阶段可以正常识别，
进入战斗部署干员阶段，使用精一或者精二原皮肤时均无法识别
在部署费用足够后有一个小的卡顿，此后会一直挂机到战斗失败
![图片](https://user-images.githubusercontent.com/125456091/219006400-f30a5e5d-7c12-424d-afc5-faae17ab8dd9.png)

**Comment by guansss** [comment]
这里是作业站网页的仓库，关于作业使用的 issue 请提到 MAA 主仓库：https://github.com/MaaAssistantArknights/MaaAssistantArknights
