### ISSUE TITLE
建议：下载原JSON时文件命名规则

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/maa-copilot-frontend#128]
以maa://21270为例
现在的规则下载为：MAACopilot_作业+代码，如MAACopilot_作业21270.json
希望增加可选项（或直接）改为：
1：作业标题，如哥伦比亚 - 实验基地机库 - 实验基地机库.json
2：（类本地编辑器）地图名_干员1+干员2，如实验基地机库_桃金娘+拉普兰德+….json
3：作战类型-地图名，如剿灭作战-实验基地机库.json
上述规则可能有语法、或其他不正确的地方，
但不论如何，主要就是想把地图（+干员）方便地写入到文件名中。

**Comment by guansss** [comment]
和 #98 的第一点差不多，不过当时只改了编辑器里面的下载，忘了改作业列表里的了
关于规则，我的想法还是一样的，加上标题就好了，如果再加上干员的话可能会太长了
