### ISSUE TITLE
“关卡名，关卡类型，关卡编号”搜索框筛选不正常

### ISSUE THREAD

**Issue by HMSRenown** [MaaAssistantArknights/maa-copilot-frontend#129]
这一框并无法完全正确的筛选关卡类型
如输入“悖论模拟”，只会显示末药的悖论模拟
![image](https://user-images.githubusercontent.com/58620808/222939603-51cc1695-115a-41c9-b3f4-3349cd4bbd29.png)

**Comment by dragove** [comment]
后端只支持单个关卡查询，已经修改逻辑支持多个关卡匹配 https://github.com/MaaAssistantArknights/MaaBackendCenter/commit/5de34df16a9d260747b5d27edd98d706dff0cace
