### ISSUE TITLE
给任意一个作业点赞后切换到其它作业，再回到刚刚点赞的作业时，作业加载失败

### ISSUE THREAD

**Issue by PieceOfFall** [MaaAssistantArknights/maa-copilot-frontend#130]
![image](https://user-images.githubusercontent.com/85009059/222949444-2e14e629-0663-4f18-abbe-2b49b2a3746b.png)

**Comment by PieceOfFall** [comment]
目测问题和生命周期相关

**Comment by guansss** [comment]
修复了，原因是以前评分成功后会返回整个operation，可以直接扔到缓存里，而现在会返回一个“评分成功”的字符串，放到缓存里就炸了（
