### ISSUE TITLE
作业编辑器中 缺少 "罗德岛临时干员" 无法清理巨蕈

### ISSUE THREAD

**Issue by Berry85** [MaaAssistantArknights/maa-copilot-frontend#131]
如题

**Comment by guansss** [comment]
这个“干员”属于装置，但目前编辑器里的干员列表并不包含装置，后面会考虑加上

现在可以先使用自定义干员名，注意名字是雇员不是干员

![image](https://user-images.githubusercontent.com/46285865/223003876-232a9510-1756-420a-af84-10b61335e614.png)

**Comment by Berry85** [comment]
了解了, 非常感謝
