### ISSUE TITLE
https://prts.plus/ 上下载的作业文件有问题

### ISSUE THREAD

**Issue by yakumoiku** [MaaAssistantArknights/maa-copilot-frontend#135]
参数名字stage_name在网站上下载的作业里默认是stageName，直接导致maa报错文件读取失败，虽然可以手动改，但是下载文件一多就改不过来了啊，能不能从源头上就把这个参数名字改回去啊

**Comment by guansss** [comment]
刚才修复了啊，你刷新下网页再试试
