### ISSUE TITLE
Do Not Combine preDelay and rearDelay

### ISSUE THREAD

**Issue by martinwang2002** [MaaAssistantArknights/maa-copilot-frontend#137]
https://github.com/MaaAssistantArknights/maa-copilot-frontend/blob/2ba1717c574fe5dbf14487ebe05ddc515aec0e46/src/components/viewer/ViewerActions.tsx#L31-L40

```
2023/3/9 15:31:30
（事实上似乎不等价，当一个操作同时采用击杀数和前置时间控制时机时。）

2023/3/9 15:32:10
你这样可以把所有的控制都用上

 /3/9 15:32:16
是个非常不错的思路

2023/3/9 15:33:28
21杀之后过16费，又过250毫秒

2023/3/9 15:35:16
我写作业的时候经常遇到99费满了，击杀数之间要放技能的情况

2023/3/9 15:35:22
这个思路一下解决问题了

2023/3/9 15:35:34
只要先写击杀数

2023/3/9 15:35:40
再写延迟时间就行
```

**Comment by martinwang2002** [comment]
@MistEO 确认一下客户端特性

**Comment by guansss** [comment]
这里合并应该只是为了简化显示，但是没有遵循 immutable 导致修改了原有的数据

现在是要把 preDelay 和 rearDealy 分开显示吗？

**Comment by martinwang2002** [comment]
感觉有这个必要

如果执行顺序是这样的

1. 条件触发
2. 等待 `preDelay`
3. 执行
4. 等待`rearDelay`

具体流程需要确认

**Comment by MistEO** [comment]
> 21杀之后过16费，又过250毫秒

现在就是这样的

**Comment by guansss** [comment]
Fixed by 53d2aa3
