### ISSUE TITLE
作业编辑器 - 子弹时间 相关描述更新

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/maa-copilot-frontend#145]
参考 https://github.com/MaaAssistantArknights/maa-website/pull/83

虽然 client 版本还没 release，但前端提前更新也没事，因为之前的子弹时间是有 bug 的，压根不能用（

https://github.com/MaaAssistantArknights/MaaAssistantArknights/commit/c4464660034f29eb315ce0e59bc667d6b0887be8

**Comment by guansss** [comment]
@martinwang2002 这个实现了吗，是否可以 close 了
