### ISSUE TITLE
新编辑器建议把 “动作序列” 里面直接铺开，而不是多一个滑动条

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/maa-copilot-frontend#157]
![S%0G1QJEIV_%5348VJYC E7](https://user-images.githubusercontent.com/18511905/235239604-1de940a5-f7ec-4087-ba9e-531f39479443.png)

动作太多的时候，一下子鼠标挪到右边划两下（整个页面的滑动条），一下子在左边划两下，很难受。建议用整个页面的滑动条，只用这一个

**Comment by UniMars** [comment]
我之前写的时候主要是有的动作长度超过页面高度，如果共用一个滑动条的话，动作序列里中间的动作编辑就显示不全了，要滑到整个页面最底下。
当然我不太懂前端，不知道是不是有其他解决办法，又或者把动作编辑页面全部压缩精简到一个页面的高度以内。

**Comment by GalvinGao** [comment]
fixed

**Comment by MistEO** [comment]
好耶好耶
