### ISSUE TITLE
作业网加个计数器的规则

### ISSUE THREAD

**Issue by ZzzHe2333** [MaaAssistantArknights/maa-copilot-frontend#159]
比如，我是大哥玩的比较多，我希望他是释放五次之后，结束有大就开这个效果。
因为如果我是ff0单奶，我充能快一点，他是别的奶，充能慢。
按击杀数来设置，少了，充能慢的就原地发愣了。多了，充能快的会一直看。按
技能释放数来解决大哥类的问题应该会好点，这样方便粗对轴，速度也快。

补充，大哥还是很厉害的，问题就是他不像山放一次技能，不像棘刺2次技能后无限(实际上是很长的有限时间)，大哥是手动5次变自动，头上还会带有技能的标志，所以MAA会一直看.....

加这个功能的话，有更多条件应该更好判断局势吧。

**Comment by ZzzHe2333** [comment]
还有可能的想法就是，内置计时器，适用于需要提前关闭大招的情况下...

**Comment by MistEO** [comment]
有“技能用法”这项动作的

**Comment by ZzzHe2333** [comment]
![Uploading QQ截图20230512132451.png…]()

**Comment by ZzzHe2333** [comment]
只有：不使用/好了就用/只用一次，然后大哥技能是自动释放...就会一直盯着大哥...

**Comment by MistEO** [comment]
你图没传上来，我是说这个，可以在某一时刻把技能改为不使用

![image](https://github.com/MaaAssistantArknights/maa-copilot-frontend/assets/18511905/33d08589-cc50-422c-b8fe-e98336972c73)

**Comment by d542Bb** [comment]
现在不是已经有了吗，怎么还不closed

**Comment by ZzzHe2333** [comment]
> 现在不是已经有了吗，怎么还不closed

忘了...
