### ISSUE TITLE
保全脚本上传打不开，也删不掉（我是作者

### ISSUE THREAD

**Issue by junyihan233** [MaaAssistantArknights/maa-copilot-frontend#161]
保全脚本上传打不开，也删不掉（我是作者

**Comment by dragove** [comment]
https://prts.maa.plus/copilot/get/23217
通过接口访问数据能正常返回，搜索貌似也正常，前端页面上看下要不先处理成不报错，能下载json，完整的支持后面再补充。

**Comment by junyihan233** [comment]
嗯嗯，能先不报错然后能把脚本下载下来就行...

**Comment by dragove** [comment]
请等待 https://github.com/MaaAssistantArknights/maa-copilot-frontend/pull/151 合并部署

**Comment by GalvinGao** [comment]
fixed in #151. 现在可以对不支持渲染详细内容的作业进行基本操作了
