### ISSUE TITLE
通过作业编辑器上传的 json 中的 中文key 会被清空

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/maa-copilot-frontend#164]
作业编辑器，点击导入本地文件，这时候显示是正常的，关掉“编辑JSON”的侧栏，再次点击“编辑JSON”，然后tool_men里的key就不见了

**Comment by MistEO** [comment]
而通过首页上传按钮直接上传的是正常的

**Comment by MistEO** [comment]
不方便发文件，贴个链接，可以用这个 json 复现 https://share.weiyun.com/tJrQihvX

**Comment by guansss** [comment]
ref: https://github.com/blakeembrey/change-case/issues/97
我修复一下

**Comment by GalvinGao** [comment]
fixed
