### ISSUE TITLE
作业详情页 评论的展示

### ISSUE THREAD

**Issue by roo12589** [MaaAssistantArknights/maa-copilot-frontend#167]
无脑抄作业(我本人)的时候，根本不关心干员和动作序列，直奔评论区

感觉干员 动作序列 评论这三者 还是评论的优先级的比较高？
是不是可以考虑吧评论提到前面 或者比如在外面设个按钮 点进后快速定位到评论区

另外有些动作序列太长，感觉也需要默认折叠一下

**Comment by guansss** [comment]
有考虑过把评论放最上面，但总觉得会有点怪，毕竟作业详情才是主要内容，而评论是附加内容

跳转按钮这个不错，不过目前还没有通过 URL 进入作业面板的功能，所以可能实现起来有点麻烦，也许可以把按钮放进作业面板里

**Comment by dragove** [comment]
干员组和动作序列或许可以添加折叠，用户一般会关心具体干员，动作序列默认和干员一样长，然后添加一个展开全部的按钮，这样应该也够用？
