### ISSUE TITLE
作业/评论区跳转直链

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/maa-copilot-frontend#169]
![image](https://github.com/MaaAssistantArknights/maa-copilot-frontend/assets/18511905/b1b3061a-3d11-4e5d-b7f5-2347a89c1697)

client 这个可以改了，准备给个链接直接让用户点，可以做到吗？

**Comment by GalvinGao** [comment]
implemented in #182
MAA那边记得找个人来做下（x
