### ISSUE TITLE
S3-6地图错误

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/maa-copilot-frontend#175]
![image](https://github.com/MaaAssistantArknights/maa-copilot-frontend/assets/74061867/6cf9d95a-b72c-4468-93b9-d607252a6591)
![image](https://github.com/MaaAssistantArknights/maa-copilot-frontend/assets/74061867/d5e888e0-3f1a-4695-a1b1-32eea18ea809)
![image](https://github.com/MaaAssistantArknights/maa-copilot-frontend/assets/74061867/62c18b20-ce8d-4be6-9d56-cee42228cf25)
没看出来这是哪关。

**Comment by guansss** [comment]
现在貌似正常了？之前可能是数据不同步，如果再次发生请重新开启 issue
