### ISSUE TITLE
我的maa上的作业就只能打开，一点都不会打就只会打开。这是什么问题呀

### ISSUE THREAD

**Issue by dofjlk** [MaaAssistantArknights/maa-copilot-frontend#179]

**Comment by GalvinGao** [comment]
没有看懂，具体是遇到什么问题了？

**Comment by dofjlk** [comment]
我的设备时macbook m2芯片，我在这个设备上下载了maa，已经连接上了。但是，当我在打开水月肉鸽时，不管我选择了什么编队，都是开局就死。只会部署一个干员。是我的maa有问题吗，还是我maa上水月肉鸽的设置有问题啊
---- Replied Message ----
| From | ***@***.***> |
| Date | 07/21/2023 13:47 |
| To | ***@***.***> |
| Cc | dofjlk ***@***.***>,
Author ***@***.***> |
| Subject | Re: [MaaAssistantArknights/maa-copilot-frontend] 我的maa上的作业就只能打开，一点都不会打就只会打开。这是什么问题呀 (Issue #179) |

没有看懂，具体是遇到什么问题了？

**Comment by GalvinGao** [comment]
唔，m2芯片，用的是playcover方案吗

**Comment by GalvinGao** [comment]
到 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/new?assignees=&labels=bug&projects=&template=cn-bug-report.yaml 报告问题吧，这里是作业站前端的 issues
