### ISSUE TITLE
搜尋幹員加個翻譯

### ISSUE THREAD

**Issue by Arcelibs** [MaaAssistantArknights/maa-copilot-frontend#181]
繁中使用者，想要在搜尋幹員這邊加個翻譯

比如說目前打繁中的「陳」，找不到「陳」
![image](https://github.com/MaaAssistantArknights/maa-copilot-frontend/assets/49543451/8fec4b09-6a27-4485-8673-9840456b89f0)

每次都要先去prts或者翻譯軟件找到簡中的「陈」
![image](https://github.com/MaaAssistantArknights/maa-copilot-frontend/assets/49543451/c427006c-04b8-45dd-bd82-948792b3910d)

好麻煩阿，這個可以怎麼改
例如說在右邊加一個欄位輸入繁體字讓他自己翻譯成簡體字?

**Comment by GalvinGao** [comment]
<img width="234" alt="image" src="https://github.com/MaaAssistantArknights/maa-copilot-frontend/assets/12567059/d49145db-6f12-4204-889b-bc4847e4a72f">
<img width="263" alt="image" src="https://github.com/MaaAssistantArknights/maa-copilot-frontend/assets/12567059/00ddd2c3-224f-4645-9fba-76fda30baa05">


已添加繁体搜索支持，感谢反馈

**Comment by GalvinGao** [comment]
另外，使用简体罗马拼音事实上也是可以搜索出对应干员的

<img width="225" alt="image" src="https://github.com/MaaAssistantArknights/maa-copilot-frontend/assets/12567059/e986a111-4b21-4933-a9f0-cbef2737f888">

**Comment by GalvinGao** [comment]
fixed in #182
