### ISSUE TITLE
希望能在作业编辑器的技能释放模块中加入血量判断功能

### ISSUE THREAD

**Issue by DrLcder** [MaaAssistantArknights/maa-copilot-frontend#183]
本人在使用作业编辑器写脚本的时候发现盾卫（包括奶盾和防盾）和奶妈都需要根据自身或攻击范围内的队友的血量来判断是否开启技能。考虑到这个功能理论上非常好实现所以我请求能在作业编辑器中加入血量判断的机制，这样能大幅提升脚本在实战中的实用性，脚本也会更加好写。

**Comment by guansss** [comment]
这个属于 MAA 客户端的功能，请提到客户端的仓库里：https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/new/choose

**Comment by AnnAngela** [comment]
需要转移到MAA仓库里吗

**Comment by guansss** [comment]
不转比较好吧，那边有 issue 模板的
