### ISSUE TITLE
自动编队bug

### ISSUE THREAD

**Issue by lssastar** [MaaAssistantArknights/maa-copilot-frontend#189]
MAA自动战斗模块

其中【自动编队】中技能选择有时会出错，遇到的是重岳选3技能，但选到了2技能

**Comment by Lixuhuilll** [comment]
这个是MAA Copilot网站的前端项目，而你碰到的问题应该是MAA本体的问题，建议去[MAA本体仓库](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues)发issues
