### ISSUE TITLE
MAA COPILOT网站的服务稳定性有问题

### ISSUE THREAD

**Issue by Coney97** [MaaAssistantArknights/maa-copilot-frontend#191]
能正常打开网页，但有时候会显示“网络错误，请检查网络连接并稍后重试”
无法加载作业内容出来

**Comment by Lixuhuilll** [comment]
前两天后端负载太高寄了，目前后端打算写首页作业缓存看能不能降低压力。另外前端向后端请求过于频繁，比如搜索的时候打一个字就发一遍请求，前端要能加个防抖的话后端压力会小很多。

**Comment by Lixuhuilll** [comment]
参见MAA Copilot后端仓库的 Issue：https://github.com/MaaAssistantArknights/MaaBackendCenter/issues/121
