### ISSUE TITLE
作业编辑器中关卡搜索搜不到TN关卡

### ISSUE THREAD

**Issue by dragove** [MaaAssistantArknights/maa-copilot-frontend#194]
接口 https://prts.maa.plus/arknights/level 正常返回了TN关卡信息，但是搜索时无搜索不到该内容

猜测原因是存在同名关卡名的问题（两条数据仅stage_id不一样）

**Comment by guansss** [comment]
引航者试炼的关卡被排除掉了，看了下历史记录，应该是当时并不支持这些关卡的作业，所以排除了，后来又支持了但是没有加回来
