### ISSUE TITLE
建议：copilot动作序列中加入退出当前战斗的选项

### ISSUE THREAD

**Issue by 8THZW** [MaaAssistantArknights/maa-copilot-frontend#195]
希望可以在copilot中可以有退出当前战斗这一新动作，目前可能的应用有：
1.对于引航者试炼等中途推出也有奖励的关卡，中途退出可以跳过困难或不稳定部分，利于快速稳定地刷取奖励；
2.可能可以与延时等执行条件配合，已达到关卡意外长时间停滞时（如乱轴导致奶盾把敌人卡在输出攻击范围外），可以在一段时间后退出该关卡，使多次刷取时能够避免偶尔的乱轴带来的大量时间损失。

**Comment by guansss** [comment]
这个属于 MAA 客户端的功能，请提到客户端的仓库里：https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/new/choose
