### ISSUE TITLE
引航者TN-4干员部署点位有偏差

### ISSUE THREAD

**Issue by 02Alive** [MaaAssistantArknights/maa-copilot-frontend#198]

**Comment by 02Alive** [comment]
![act3bossrush_04](https://github.com/MaaAssistantArknights/maa-copilot-frontend/assets/105614344/bbf6094c-13bc-4087-93a0-fbc6670dfa44)
运行自动战斗时干员放置纯在偏差导致放不上去

**Comment by guansss** [comment]
这个属于 MAA 客户端的功能，请提到客户端的仓库里：https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/new/choose
