### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by trndsttr7777** [MaaAssistantArknights/maa-copilot-frontend#209]
建议MAA copilot-Beta的自动战斗功能，可以增加以下功能

检测一下当前选中的关卡是否与作业的关卡相符

**Comment by trndsttr7777** [comment]
甚至可以帮忙检查一下干员有没有带错

**Comment by guansss** [comment]
客户端的功能建议请发到 MAA 主仓库里：https://github.com/MaaAssistantArknights/MaaAssistantArknights
