### ISSUE TITLE
咱这网站有暗色模式吗

### ISSUE THREAD

**Issue by GreatDianna** [MaaAssistantArknights/maa-copilot-frontend#218]
半夜抄作业被闪到了，没看到有切换的，开插件或者实验功能感觉糊成一片，而且可能有人不用那个？
呃也没那么重要就是了

**Comment by roo12589** [comment]
我自用的这个有，查作业可以用 [naive-copilot-frontend.vercel.app](https://naive-copilot-frontend.vercel.app/)

**Comment by GreatDianna** [comment]
> 我自用的这个有，查作业可以用 [naive-copilot-frontend.vercel.app](https://naive-copilot-frontend.vercel.app/)

好好好
