### ISSUE TITLE
自动战斗中可以加入选好友助战的功能吗？

### ISSUE THREAD

**Issue by CGYR** [MaaAssistantArknights/maa-copilot-frontend#242]
需求：借好友助战抄作业+多轮次自动战斗，方便低配号代理刷图
考虑到自动肉鸽可以借助战，在自动战斗里面加上助战选人应该是可行的？

**Comment by guansss** [comment]
客户端的功能建议请发到 MAA 主仓库里：https://github.com/MaaAssistantArknights/MaaAssistantArknights
