### ISSUE TITLE
Bottom half of page is blank when search result is few. / 搜索结果过少时网页下半空白区域颜色不正常

### ISSUE THREAD

**Issue by momoblydblk** [MaaAssistantArknights/maa-copilot-frontend#248]
![图片](https://github.com/MaaAssistantArknights/maa-copilot-frontend/assets/21081757/81618207-f373-4816-8161-12985be1a62a)
如图，网页下半部分颜色不一致。
As in the pic, the bottom half has different color comparing to the rest of the page.

**Comment by hmydgz** [comment]
> ![图片](https://private-user-images.githubusercontent.com/21081757/297920462-81618207-f373-4816-8161-12985be1a62a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NDQ4NjAsIm5iZiI6MTcwNTc0NDU2MCwicGF0aCI6Ii8yMTA4MTc1Ny8yOTc5MjA0NjItODE2MTgyMDctZjM3My00ODE2LTgxNjEtMTI5ODViZTFhNjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDA5NTYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwNGI2MDNjOTAxNGY1NDJlZjYzNDI3ODVmZjRiZWNkZTBkMzJiNTQxOTVhZmVlMjY5NmVhN2Y2OWYzMGM0NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n4fZtid6Blgl_EoPAhmywnknfA8mHrordxEOlmxwFPk) 如图，网页下半部分颜色不一致。 As in the pic, the bottom half has different color comparing to the rest of the page.

#246 的 e43b710c34963ad6a26aba6afc2d2101cec165df 中有修复
