### ISSUE TITLE
搜索排序有点问题

### ISSUE THREAD

**Issue by unlimitwhitenight** [MaaAssistantArknights/maa-copilot-frontend#250]
搜索HS-9的时候，排序变成了HS-1第一，拉到下面才有HS-9
![image](https://github.com/MaaAssistantArknights/maa-copilot-frontend/assets/14921482/67048c39-943b-4392-9a40-118be2b1d022)

**Comment by dragove** [comment]
关卡用第二个搜索条件吧，根据内容搜索的话会检索到关键字，HS-1的作业描述里带有 HS-9 的字样，这个作业热度也确实比 HS-9 的高，所以出现了这个结果
