### ISSUE TITLE
希望能修改一下肉鸽奶盾的优先级

### ISSUE THREAD

**Issue by umeGe** [MaaAssistantArknights/maa-copilot-frontend#251]
现在有黍的情况下根据黍和塞雷亚的强度对比，黍的优先级应该比塞雷亚高，希望能更新一下肉鸽里优先级的设置

**Comment by guansss** [comment]
客户端的功能建议请发到 MAA 主仓库里：https://github.com/MaaAssistantArknights/MaaAssistantArknights
