### ISSUE TITLE
搜索干员

### ISSUE THREAD

**Issue by LiamSho** [MaaAssistantArknights/maa-copilot-frontend#27]
[MaaAssistantArknights/MaaCopilotServer v2.3.0](https://github.com/MaaAssistantArknights/MaaCopilotServer/releases/tag/2.3.0)

检索作业可以包含关于干员的检索，`operator={expression}`

关于 expression:

- `A` 将返回 ***干员列表中，名字中含有 A 的*** 作业
- `~A` 将返回 ***干员列表中，名字中不含有 A 的*** 作业
- `A,~B` 将返回 ***干员列表中，名字中不含有 B 的，但是含有 A 的*** 作业

多个 condition 使用 `,` 分隔，以 `~` 开头的 condition 为 Exclude，其余为 Include，所有 Exclude 将优先于 Include 执行，即现使用 Exclude 的条件进行检索，然后在结果中再按照 Include 的条件进行检索

**Comment by GalvinGao** [comment]
多个 querystring 组成的查询条件是 `AND` 连接吗？比如 `level_keyword=IC-EX-7&operator=阿米娅` 是 `IC-EX-7 AND 阿米娅` 还是 `IX-EX-7 OR 阿米娅`

**Comment by LiamSho** [comment]
> 多个 querystring 组成的查询条件是 `AND` 连接吗？比如 `level_keyword=IC-EX-7&operator=阿米娅` 是 `IC-EX-7 AND 阿米娅` 还是 `IX-EX-7 OR 阿米娅`

全部是 AND

**Comment by LiamSho** [comment]
`IX-EX-7 OR 阿米娅` 有意义吗（

**Comment by GalvinGao** [comment]
Just to make sure 毕竟HTTP状态码都能打死都200（吐槽
