### ISSUE TITLE
为什么maa作业网站一直加载失败，别的网站正常

### ISSUE THREAD

**Issue by Gnarrrrr** [MaaAssistantArknights/maa-copilot-frontend#270]
![1000066669](https://github.com/MaaAssistantArknights/maa-copilot-frontend/assets/157442594/0616e030-d243-4960-89e0-e6fa22c06129)

**Comment by Gnarrrrr** [comment]
求求了，呜呜没法抄作业好久了

**Comment by guansss** [comment]
https://prts.maa.plus/
https://ota.maa.plus/

这两个网址你看看能不能访问
