### ISSUE TITLE
无法删除作业&作业集无法取消勾选作业

### ISSUE THREAD

**Issue by ntgmc** [MaaAssistantArknights/maa-copilot-frontend#274]
maa://22578无法查看详细信息，修改，删除
作业集管理中，左边一列的作业取消勾选后无法保存

**Comment by guansss** [comment]
> 无法查看详细信息，修改，删除

这个的具体表现是啥，我这里好像没问题

**Comment by guansss** [comment]
奇怪了，你试试用这个链接能不能获取到：
https://prts.maa.plus/copilot/get/22578

**Comment by ntgmc** [comment]
> 奇怪了，你试试用这个链接能不能获取到： https://prts.maa.plus/copilot/get/22578

这个可以

**Comment by dragove** [comment]
后端迁移数据的问题，迁移的数据没经过测试，现已尝试更正，麻烦再确认一下是否还报错

**Comment by ntgmc** [comment]
> maa://22578

可以了
