### ISSUE TITLE
MAA Copilot 作业 5星德克萨斯带寒冬信使皮肤无法部署

### ISSUE THREAD

**Issue by drrrx5** [MaaAssistantArknights/maa-copilot-frontend#287]
MAA Copilot 作业 5星德克萨斯带寒冬信使皮肤无法部署 换成原皮可以
6星术士艾雅法拉带精一原皮无法部署 换成精二皮肤可以

**Comment by ntgmc** [comment]
与作业站及作业无关，为MAA缓存问题，删除cache\avatars即可
