### ISSUE TITLE
自动运行生息演算时出问题

### ISSUE THREAD

**Issue by 5786qybf** [MaaAssistantArknights/maa-copilot-frontend#296]
每次使用生息演算功能的时候都会在进入第一张资源图后报错。
使用的版本是5.2.3，已尝试过重新下载，但并未解决问题。
无论是b服还是官服都会出现同样的问题。
使用到的模拟器是mumu12。

模拟器报错截图如下：
https://i.postimg.cc/dQhkhj5h/20240505001227.png

希望大佬有空能解决下吧，谢谢大佬。

**Comment by martinwang2002** [comment]
请前往主仓库提出issue 并提供日志。感谢
[github.com/MaaAssistantArknights/MaaAssistantArknights](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/new/choose)

**Comment by 5786qybf** [comment]
已经有人提出同样的issue，我这里就不重复提交了：生息演算自动到第一天结束前后出错 · Issue #9335 · MaaAssistantArknights/MaaAssistantArknights (github.com)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaaAssistantArknights/maa-copilot-frontend"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月13日(星期四) 凌晨5:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaaAssistantArknights/maa-copilot-frontend] 自动运行生息演算时出问题 (Issue #296)





 
请前往主仓库提出issue 并提供日志。感谢
 github.com/MaaAssistantArknights/MaaAssistantArknights
