### ISSUE TITLE
输入地图名后，映射到 levelId，然后显示跳转 map prts 的链接？

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/maa-copilot-frontend#3]
link to https://github.com/Houdou/prts-map/issues/39

双赢，win win 哒！

**Comment by martinwang2002** [comment]
Martin Wang 2022/9/25 10:40:52
maa用的是levelid

Guan 2022/9/25 10:41:01
sub-1-1 和 s01

Martin Wang 2022/9/25 10:41:06
prts那边可能是stage_id

![7A%E 69@FMVOHHK9JVNI5HS](https://user-images.githubusercontent.com/29770303/192216524-066cbf01-0e89-4d0c-9f90-be17ad648443.png)


Martin Wang 2022/9/25 10:47:52
前端数据都是从后端来的

Martin Wang 2022/9/25 10:48:04
后端数据都是从上面的仓库来的

Martin Wang 2022/9/25 10:48:10
所以如果要stageid

Martin Wang 2022/9/25 10:48:14
还得后端搞

Martin Wang 2022/9/25 10:48:24
先不搞那个feature

Guan 2022/9/25 10:49:11
行吧，那就先鸽掉了
