### ISSUE TITLE
深色模式下Tooltip2的背景与文本颜色相近，导致看不清文本内容

### ISSUE THREAD

**Issue by ssoda01** [MaaAssistantArknights/maa-copilot-frontend#310]
<img width="304" alt="image" src="https://github.com/MaaAssistantArknights/maa-copilot-frontend/assets/96223880/d07f089e-adab-44a3-a71e-9f7e240416c7">

**Comment by Wanniki** [comment]
Tooltip2  组件样式接收 element 元素时样时无法穿透
![image](https://github.com/MaaAssistantArknights/maa-copilot-frontend/assets/83859105/f096c433-4fba-49f5-9b7f-751b092d8c07)
