### ISSUE TITLE
当作业内容超长时同行作业布局空位较大

### ISSUE THREAD

**Issue by Wanniki** [MaaAssistantArknights/maa-copilot-frontend#314]
当一个较长的作业和一个较短的作业出现在同一行时，较短的作业底部布局空洞，如果让内容去自适应高度会不会更好些。

![image](https://github.com/MaaAssistantArknights/maa-copilot-frontend/assets/83859105/52855afb-d4ff-4b8e-97f6-074d00906766)

**Comment by Handiwork** [comment]
我提交的 PR 是标题居顶，干员/干员组及以下组件居底部，内容自适应垂直居中的，不知道被谁改成这样（

**Comment by aojunhao123** [comment]
视觉观感上确实差了点，我看看咋修（

**Comment by Handiwork** [comment]
#319
