### ISSUE TITLE
刷理智功能，备选关卡，希望能设置多几个关卡选项

### ISSUE THREAD

**Issue by chenjiu111** [MaaAssistantArknights/maa-copilot-frontend#344]
如题，例如我的关卡选择是剿灭，备选1是红票-5，备选2是奶盾芯片组，但今天红票和奶盾芯片组都没有，我想刷近特芯片组，希望再多一个备选，感谢各位开发组大佬

**Comment by Daydreamer114** [comment]
这里是作业站前端，有问题请去 maa 主仓库提 issue
