### ISSUE TITLE
关于MAA Copliot后端接口prts.maa.plus的SSL/TLS问题

### ISSUE THREAD

**Issue by mikoto2464** [MaaAssistantArknights/maa-copilot-frontend#351]
### 问题描述
使用代理访问 https://prts.plus/ 时会出现如下错误
![图片](https://github.com/user-attachments/assets/8309b3de-125d-46a8-8054-5eaab292ad65)

### 问题排查

1. 发现问题出现在prts.maa.plus后端接口似乎没有返回结果，并且提示CORS Failed
![图片](https://github.com/user-attachments/assets/a615de87-f2d3-4e96-b9c2-b2b8e1af8f8f)
> 怀疑浏览器CORS策略问题？
> 服务器屏蔽国外请求？
> DNS国内外解析错误？
> TLS版本不匹配？
> 本机网络环境问题？

2. http测试发现，并无国内外请求的限制，并且所有ip都解析到`8.218.106.121`，同时也排除了DNS的问题
![图片](https://github.com/user-attachments/assets/4ff196a2-0845-4d07-a018-efcb46fe5561)

3. 不使用代理，tcping 443端口正常访问
> `> tcping 8.218.106.121 443`
>
> ![图片](https://github.com/user-attachments/assets/892b9b56-4bc3-4c53-b61b-f2d44f643a0f)

4. 使用代理，tcping 443端口同样正常访问，说明并不是在http请求上出现问题，判断大概率是SSL相关问题
> `> tcping 8.218.106.121 443 -proxy-server 127.0.0.1 -proxy-port 7891`
>
> ![图片](https://github.com/user-attachments/assets/aef7eaff-ec7a-4638-aa44-093e07d8f125)

5. 不使用代理，使用curl测试，正常访问，本机当前curl的加密套件并无问题
> `> curl -v https://prts.maa.plus/`
>
> ![图片](https://github.com/user-attachments/assets/c5c8cae2-7044-416a-b868-b6c295e28852)

6. 使用代理，使用curl测试，出现错误
`schannel: failed to receive handshake, SSL/TLS connection failed`
服务器并未返回握手信息，是此台服务器对我的代理服务器的请求被阻止了吗？
> `> curl -v https://prts.maa.plus/ -x http://127.0.0.1:7891`
>
>![图片](https://github.com/user-attachments/assets/985cfd1a-d36b-4d2c-983e-63b4fd48f791)

7. 在服务器上，使用curl测试，访问正常，并不是代理服务器与maa服务器之间的问题。
也就是说，问题出现在本机与代理服务器之间的通信问题，通信使用的是hysteria2协议，尝试更换协议能否解决问题？
> `> curl https://prts.maa.plus`
>
> ![图片](https://github.com/user-attachments/assets/555822a5-ebaa-4132-baae-25f9b39ac8f2)

8. 更换为机场的`vless + xtls-rprx-vision + reality`配置（懒得再搭）再次测试。发现此时能够正常访问。
> `> curl -v https://prts.maa.plus/ -x http://127.0.0.1:7891`
>
> ![图片](https://github.com/user-attachments/assets/2611b171-94e3-4a6c-8f7f-7539aaf578ee)

### 问题总结
个人技术能力有限，知识范围也不足，目前貌似看来问题出在hysteria2协议或者我clash核心实现的问题？但是我使用此hysteria2代理访问其他网站，使用prts.maa.plus正在使用的TLS1.3时并未出现相关问题。但是此例仍可看出prts.maa.plus仍然可能存在SSL/TLS兼容问题。
![图片](https://github.com/user-attachments/assets/41a74e4a-896a-40ab-a876-f31695c1dc77)

### 相关issue
#308 #302 #293

**Comment by mikoto2464** [comment]
补充一下测试的环境，以便复现
- 客户端：`FlClash 0.8.63` [项目地址](https://github.com/chen08209/FlClash)
- 内核：`mihomo（Clash.Meta）`[项目地址](https://github.com/chen08209/Clash.Meta/tree/FlClash)
- proxy配置
{ name: '_name_', server: _ip_, port: 443, sni: _domain_, up: 5000, down: 5000, skip-cert-verify: false, type: hysteria2, password: _password_ }

**Comment by ABA2396** [comment]
这两天才开始遇到的，不配代理也有概率遇到（maa里神秘代码拉文件的时候），但是重复几次又能成功

**Comment by mikoto2464** [comment]
按理说貌似得在https://github.com/MaaAssistantArknights/MaaBackendCenter提这个issue（
我去隔壁重发一个好了
