### ISSUE TITLE
作业自动编队不认识维什戴尔

### ISSUE THREAD

**Issue by hjtczyj** [MaaAssistantArknights/maa-copilot-frontend#358]
MAA自动战斗时，有的作业找不到维什戴尔，提示缺少干员错误。

**Comment by Saratoga-Official** [comment]
维什戴尔如果有特别关注的话就取消了，而且这也不是作业站的问题，是maa本身识别错了，提issue的地方就不对

**Comment by hjtczyj** [comment]
> 维什戴尔如果有特别关注的话就取消了，而且这也不是作业站的问题，是maa本身识别错了，提issue的地方就不对

Sorry，新人不太清楚在哪里提
