### ISSUE TITLE
搜索 EP-EX-8 时结果不正常

### ISSUE THREAD

**Issue by chesha1** [MaaAssistantArknights/maa-copilot-frontend#359]
![image](https://github.com/user-attachments/assets/4d44644d-792c-47eb-9b87-22b0cc7b7ec1)

**Comment by chesha1** [comment]
搜索别的关卡都正常，用 F12 看了下请求，确认已经对 `/copilot/query` 发起请求得到了响应，不是前端的显示问题

**Comment by Saratoga-Official** [comment]
因为作业简介里有EX8，就会这样，你可以用第二个关卡搜索框搜
