### ISSUE TITLE
UI BUG

### ISSUE THREAD

**Issue by Shawnsdaddy** [MaaAssistantArknights/maa-copilot-frontend#72]
![image](https://user-images.githubusercontent.com/33809511/197115293-4946354c-9fed-493b-8c4c-9541ae1b39b5.png)

如果选择蜜莓则出来的是清平
![image](https://user-images.githubusercontent.com/33809511/197115369-1b0d2e11-f4ce-4793-8e09-aeeaa5a4bcb4.png)

![image](https://user-images.githubusercontent.com/33809511/197115392-26a0bd77-27c3-4bf3-85fd-e1fa2a2e208f.png)

**Comment by Shawnsdaddy** [comment]
不知道是什么奇怪的BUG

**Comment by guansss** [comment]
看起来是输入法的原因，输入框失焦时，没打出来的拼音被清空导致列表重置，我加个 debounce 应该就好了

**Comment by Shawnsdaddy** [comment]
我也觉得是输入法问题
