### ISSUE TITLE
作业编辑器设置干员技能好了就放，测试一下结果不会自动使用技能

### ISSUE THREAD

**Issue by yebing233** [MaaAssistantArknights/maa-copilot-frontend#73]
作业编辑器设置干员技能好了就放，测试一下结果不会自动使用技能

这是视频链接: https://pan.baidu.com/s/17MrrlOFoa0EZnVGYZpq23g?pwd=n3eg 提取码: n3eg

**Comment by guansss** [comment]
![image](https://user-images.githubusercontent.com/46285865/197374105-615fd4f3-16cc-47b4-ae93-de383a43aff3.png)

要在最后加一个开始挂机的动作
