### ISSUE TITLE
加载失败

### ISSUE THREAD

**Issue by Tzeao** [MaaAssistantArknights/maa-copilot-frontend#81]
![image](https://user-images.githubusercontent.com/78530440/200341107-e195cb52-e72e-4da1-8d68-ca3c98147fcf.png)

**Comment by guansss** [comment]
服务器寄了，正在修复中

**Comment by ldcivan** [comment]
是服务器本身的问题抑或是架构的问题？如果是前者的话我可以提供一部闲置的服务器

**Comment by ldcivan** [comment]
> 服务器寄了，正在修复中

是服务器本身的问题抑或是架构的问题？如果是前者的话我可以提供一部闲置的服务器

**Comment by guansss** [comment]
我不到啊😟 @ChingCdesu 救救！

**Comment by ChingCdesu** [comment]
正在修，不是服务器的问题。
是postgresql的HA有点小毛病，正在弄迁移，迁移到非HA部署

**Comment by congealPlume** [comment]
是又寄了嘛  昨天似乎是好的？
