### ISSUE TITLE
有没有QQ群呀

### ISSUE THREAD

**Issue by ZeroBlock0** [MaaAssistantArknights/maa-copilot-frontend#83]
如题

**Comment by ntgmc** [comment]
你想干嘛⊙(・◇・)？

**Comment by guansss** [comment]
写作业/开发者群：1169188429

抄作业群：
![5`WH %9WRR%0DO%RWD3LYJG](https://user-images.githubusercontent.com/46285865/200809347-6ed2eed7-15d5-40dc-a3c0-dc968f48ffb7.png)
https://github.com/MaaAssistantArknights/MaaAssistantArknights#%E5%B9%BF%E5%91%8A
