### ISSUE TITLE
自动战斗作业分享修改建议

### ISSUE THREAD

**Issue by Lappland1111** [MaaAssistantArknights/maa-copilot-frontend#87]
把每个关卡和自动战斗地图坐标一样进行分类
关卡从练度从低到高进行排列好进行选择

**Comment by guansss** [comment]
没看懂，可以详细描述一下吗

**Comment by Lappland1111** [comment]
| |
18979109423
|
|
***@***.***
|
把每个关卡作业跟方舟一样放进 章节总览一样如图然后点进对应章节进入关卡比如1-1进入就是作业练度由低到高排序   如果可以的话在加个自己选择自己有的干员总览库由这个基础更好的筛选作业更加完善作业筛选最好是分大小号仓库





---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年11月17日 01:42 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [MaaAssistantArknights/maa-copilot-frontend] 自动战斗作业分享修改建议 (Issue #87) |

没看懂，可以详细描述一下吗

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

从 网易邮箱大师 发来的云附件
|
| |
| |
|
| |
| 明日方舟 - PRTS.地图 - 个人 - Microsoft Edge 2022_11_17 2_08_41.png |
| |
| (761.9KB,2022年12月2日 2:17 到期) |
| |
| 下载 |
| |
| |
