### ISSUE TITLE
通常来说，未写明难度的作业均同时支持突袭及普通两个难度

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/maa-copilot-frontend#9]
真的（

![image](https://user-images.githubusercontent.com/18511905/184502971-590b35dc-a6f1-4152-a536-6bb307d2ac92.png)

**Comment by GalvinGao** [comment]
蛤 真的吗

**Comment by MistEO** [comment]
真的，现在群文件里的所有作业都是这样

**Comment by GalvinGao** [comment]
原来是这样 那我改一下
