### ISSUE TITLE
干员搜索框正反选效果错误

### ISSUE THREAD

**Issue by BTreeNewBee** [MaaAssistantArknights/maa-copilot-frontend#91]
![maa2](https://user-images.githubusercontent.com/18378664/202670663-d3df07fb-9d28-4e86-ae3b-d6b7d26f0fe3.gif)
添加鸡翅时将反选的山给取代了，山变成了正选而鸡翅变成了反选

**Comment by FutabaRio** [comment]
看了下这个 bug 造成的原因 ，反选的时候是设置的选择列表 index 的 exclude 字段为 true， 如 gif 图所示，先设置了index 1，2 为 true 在添加棘刺的时候把棘刺插到了 index 2的位置，显示就直接排除了。
