### ISSUE TITLE
请问能加上潜能计算吗

### ISSUE THREAD

**Issue by O-P-F** [MaaAssistantArknights/maa-copilot-frontend#94]
危机合约里边潜能减部署费用的差距太大了

**Comment by guansss** [comment]
没必要吧
如果作业里的潜能比较高，那么应该由作者来预留额外费用的空间
如果作业里的潜能比较低，那么就算你自己的潜能更高导致费用提前满足，也不应该提前部署，不然后面的轴就对不上了
