### ISSUE TITLE
在干员列表添加干员之后技能选择与下拉框不一致

### ISSUE THREAD

**Issue by status102** [MaaAssistantArknights/maa-copilot-frontend#97]
操作流程：
选择一名干员，选择技能二 / 三，然后点击添加。技能选择重新回到技能一，但是下拉框不会重置为技能一。技能用法则没有这种情况

![image](https://user-images.githubusercontent.com/102887808/203573547-87958e2b-ca49-4f83-b07b-4e4dc3bbd3ba.png)

**Comment by status102** [comment]
部署干员的干员朝向也有这个问题

**Comment by guansss** [comment]
是组件库的 bug (or feature)：https://github.com/palantir/blueprint/issues/3989
