### ISSUE TITLE
请求追加一些小功能

### ISSUE THREAD

**Issue by status102** [MaaAssistantArknights/maa-copilot-frontend#98]
1. 下载作业的时候，文件名能重命名为"标题+干员.json"
2. 在不能连接到MAA的时候能够正常输入地图名称（第11次危机合约刚开的时候想来用在线的作业编辑器，但是输不进地图名
3. 希望能够在输入地图名称之后，在下方提供一个跳转到地图信息map.ark-nights.com对应页面的链接
4. 希望在添加干员的时候，对于干员的技能能够提供一定的展现，比如图标？名字？（可能图标会更熟悉一点

**Comment by guansss** [comment]
> 下载作业的时候，文件名能重命名为"标题+干员.json"

标题可以，但加上干员的话可能会太长了

> 在不能连接到MAA的时候能够正常输入地图名称（第11次危机合约刚开的时候想来用在线的作业编辑器，但是输不进地图名

现在有计划给关卡列表做缓存了（画饼

> 希望能够在输入地图名称之后，在下方提供一个跳转到地图信息map.ark-nights.com对应页面的链接

参考 #3，目前两边的关卡 ID 格式不一样所以没有做
现在的计划是直接嵌入 Theresa.wiki 的地图：https://github.com/martinwang2002/Theresa-wiki/issues/1 ，正在制作中

> 希望在添加干员的时候，对于干员的技能能够提供一定的展现，比如图标？名字？（可能图标会更熟悉一点

技能名字未必有多少人记得住（红蒂二技能叫什么？），更别说图标了，还是直接数字的辨识度比较高
