### ISSUE TITLE
为什么自动战斗会把凛冬识别成琴柳

### ISSUE THREAD

**Issue by GNbulldozer** [MaaAssistantArknights/maa-copilot-frontend#99]
![QQ截图20221124035104](https://user-images.githubusercontent.com/31914684/203634974-b78df992-d419-4b9a-98fa-c3744c645dd7.png)
是哪里操作有问题么

**Comment by GNbulldozer** [comment]
![QQ截图20221124040507](https://user-images.githubusercontent.com/31914684/203637290-b13f96db-39cd-4894-b1d3-56a72fbf4722.png)
更新了版本还是不行
下面是json文件
{
  "minimum_required": "v4.0.0",
  "actions": [
    {
      "type": "Deploy",
      "name": "琴柳",
      "location": [
        2,
        1
      ],
      "direction": "Right"
    },
    {
      "type": "Skill",
      "name": "琴柳",
      "cost_changes": 0
    },
    {
      "type": "Deploy",
      "name": "晓歌",
      "location": [
        3,
        1
      ],
      "direction": "Right"
    },
    {
      "type": "Skill",
      "name": "晓歌"
    },
    {
      "type": "Deploy",
      "name": "风笛",
      "location": [
        1,
        1
      ],
      "direction": "Right"
    },
    {
      "type": "Deploy",
      "name": "玛恩纳",
      "location": [
        4,
        1
      ],
      "direction": "Down"
    },
    {
      "type": "Skill",
      "name": "风笛"
    },
    {
      "type": "Deploy",
      "name": "极境",
      "location": [
        2,
        2
      ],
      "direction": "Right"
    }
  ],
  "doc": {
    "title": "玻利瓦尔 - 在建沙滩 - 在建沙滩"
  },
  "groups": [],
  "opers": [
    {
      "name": "琴柳",
      "skill": 3,
      "skill_usage": 0
    },
    {
      "name": "晓歌",
      "skill": 2,
      "skill_usage": 1
    },
    {
      "name": "银灰",
      "skill": 3,
      "skill_usage": 0
    },
    {
      "name": "玛恩纳",
      "skill": 3,
      "skill_usage": 0
    },
    {
      "name": "极境",
      "skill": 2,
      "skill_usage": 0
    },
    {
      "name": "风笛",
      "skill": 3,
      "skill_usage": 0
    },
    {
      "name": "瑕光",
      "skill": 2,
      "skill_usage": 0
    },
    {
      "name": "灵知",
      "skill": 3,
      "skill_usage": 0
    },
    {
      "name": "铃兰",
      "skill": 3,
      "skill_usage": 0
    },
    {
      "name": "塞雷娅",
      "skill": 3,
      "skill_usage": 0
    },
    {
      "name": "史尔特尔",
      "skill": 3,
      "skill_usage": 0
    },
    {
      "name": "阿",
      "skill": 3,
      "skill_usage": 0
    }
  ],
  "stage_name": "obt/rune/level_rune_13-01"
}

**Comment by GNbulldozer** [comment]
带德狗就不会识别错误 好怪

**Comment by guansss** [comment]
运行时错误请在MAA主仓库那边提issue
